# Generated by Django 4.0.4 on 2022-06-08 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotasFiscai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_NFE', models.CharField(max_length=100)),
                ('Nome_Emissor', models.CharField(max_length=100)),
                ('Emissor_CNPJ', models.PositiveBigIntegerField()),
                ('Nome_Destinatario', models.CharField(max_length=100)),
                ('CNPJ_ou_CPF_Destinatario', models.PositiveBigIntegerField()),
                ('Produto', models.CharField(max_length=100)),
            ],
        ),
    ]
