# Generated by Django 4.0.4 on 2022-06-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notasfiscai',
            name='CNPJ_ou_CPF_Destinatario',
        ),
        migrations.AlterField(
            model_name='notasfiscai',
            name='Emissor_CNPJ',
            field=models.CharField(max_length=18),
        ),
    ]
