# Generated by Django 4.0.4 on 2022-06-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0002_remove_notasfiscai_cnpj_ou_cpf_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notasfiscai',
            name='Valor',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
