# Generated by Django 4.0.4 on 2022-06-08 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='CPF_ou_CNPJ',
        ),
    ]
