# Generated by Django 4.0.4 on 2022-06-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Telefone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
